### ISSUE TITLE
Сверстать кнопку

### ISSUE THREAD

**Issue by rLukoyanov** [CoffeeMapper/frontend#8]
Сверстать кнопку согласно [макету](https://www.figma.com/file/1yRinCIUjk6wyOpoMG0OFh/ui-kit?type=design&node-id=408-26861&mode=design&t=8mZLY3Xispo6G1zO-4)

Кнопка должна иметь состояния `hover`, `focused`, `pressed`, `disabled`

<img width="1075" alt="Screenshot 2024-02-23 at 16 42 25" src="https://github.com/CoffeeMapper/frontend/assets/105169805/62ad5af1-687b-4065-b282-07da1f00b870">

**Comment by Artematrr** [comment]
@rLukoyanov
